/** @format */

const translationEn = {
	home: 'Home',
	about: 'About',
	films: 'Filmography',
	contacts: 'Contacts',
	filmsList: 'List of films',
	addFilm: 'Add film',
	contactsList: 'List of contacts',
	addContact: 'Add contact',
	forgotPassword: 'Reset Password',
	vision: 'Vision',
	visionDescription:
		'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make',
	ethics: 'Ethics',
	ethicsDescription:
		'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make',
	team: 'The team',
	teamDescription:
		'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make',
	genericInfo: {
		name: 'Name',
		surname: 'Surname',
		email: 'Email',
		number: 'Telephone number',
	},
	password: 'Password',
	confirmPassword: 'Confirm password',
	title: 'Title',
	director: 'A film by',
	productions: 'Production',
	producers: 'Producers',
	coProductions: 'Co-production',
	coProducers: 'Co-producers',
	screenwriter: 'Screenwriting',
	genres: 'Genre',
	directorOfPhotography: 'Photography',
	editing: 'Editing',
	scenography: 'Scenography',
	costumes: 'Costumes',
	music: 'Music',
	sound: 'Sound',
	soundDesign: 'Sound design',
	casting: 'Casting',
	lineProducer: 'Line producer',
	executiveProducers: 'Executive Producers',
	distributor: 'Distributor',
	salesAgent: 'Sales agent',
	firstAssistantDirector: 'First assistant director',
	synopsis: 'Synopsis',
	productionNotes: 'Production Notes',
	duration: 'Duration',
	minutes: 'Minutes',
	year: 'Year',
	typology: 'Typology',
	festivals: 'Festivals',
	links: 'Links',
	competition: 'In Competition',
	award: 'Award',
	productionsLabels: {
		production: 'Production',
		addProduction: 'Add production',
		deleteProduction: 'Delete production',
	},
	producersLabels: {
		producer: 'Producer',
		addProducer: 'Add producer',
		deleteProducer: 'Delete producer',
	},
	coProductionsLabels: {
		coProduction: 'Co-production',
		addCoProduction: 'Add co-production',
		deleteCoProduction: 'Delete co-production',
	},
	coProducersLabels: {
		coProducer: 'Co-producer',
		addCoProducer: 'Add co-producer',
		deleteCoProducer: 'Delete co-producer',
	},
	screenwritersLabels: {
		screenwriter: 'Screenwriter',
		addScreenwriter: 'Add screenwriter',
		deleteScreenwriter: 'Delete screenwriter',
	},
	festivalsLabels: {
		festival: 'Festival',
		addFestival: 'Add festival',
		deleteFestival: 'Delete festival',
	},
	executiveProducersLabels: {
		executiveProducer: 'Executive Producer',
		addExecutiveProducer: 'Add Executive Producer',
		deleteExecutiveProducer: 'Delete Executive Producer',
	},
	cover: 'Film cover',
	profileCover: 'Profile picture',
	role: 'Role',
	bio: 'Biography',
	insertAction: 'Insert',
	modifyAction: 'Modify',
	confirmAction: 'Confirm',
	signInAction: 'Sign in',
	createAccount: 'Create account',
	modify: 'Modify',
	remove: 'Remove',
	labels: {
		signUpLabel: 'Create your account',
		loginLabel: 'Login',
		passwordLabel: 'Insert the new password',
		forgotLabel: 'If you had forget the password click here',
		emailLabel: 'Insert your email',
		addDbFilm: 'Add a film inside the database',
		modifyDbFilm: 'Modify a film inside the database',
		addDbContact: 'Add a contact inside the database',
		modifyDbContact: 'Modify a contact inside the database',
	},
	links: {
		trailer: 'Trailer',
		imdb: 'Link imdb',
		instagram: 'Link instagram',
		facebook: 'Link facebook',
	},
	errors: {
		dbCrud:
			'Problem during the compilation of the database, try to fill the form again',
		signUp:
			'Problem during the account creation, try to compile the form again.',
		login: 'Problem during the sign in, try to compile the form again.',
		forgotPassword:
			'Problem during the request of password reset, try to make a new request',
		resetPassword:
			'Problema during the reset of the password, try to make a new request',
		filmError: 'The film selected was not found, go back to the previous page',
		contactError:
			'The contact selected was not found, go back to the previous page',
	},
};

export { translationEn };
