/** @format */

const translationIt = {
	home: 'Home',
	about: 'Il team',
	films: 'Filmografia',
	contacts: 'Contatti',
	filmsList: 'Lista dei film',
	addFilm: 'Aggiungi un film',
	contactsList: 'Lista dei contatti',
	addContact: 'Aggiungi un contatto',
	forgotPassword: 'Reimposta la password',
	vision: 'Visione',
	visionDescription:
		'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make',
	ethics: 'Etica',
	ethicsDescription:
		'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make',
	team: 'Il team',
	teamDescription:
		'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make',
	genericInfo: {
		name: 'Nome',
		surname: 'Cognome',
		email: 'Email',
		number: 'Numero di telefono',
	},
	password: 'Password',
	confirmPassword: 'Conferma password',
	title: 'Titolo',
	director: 'Regia',
	productions: 'Produzione',
	producers: 'Produttori',
	coProductions: 'Co-produzione',
	coProducers: 'Co-produttori',
	actors: 'Attori',
	subject: 'Soggetto',
	screenwriter: 'Sceneggiatura',
	genres: 'Genere',
	directorOfPhotography: 'Fotografia',
	editing: 'Montaggio',
	scenography: 'Scenografia',
	costumes: 'Costumi',
	music: 'Musiche',
	sound: 'Suono',
	soundDesign: 'Design del suono',
	casting: 'Casting',
	lineProducer: 'Organizzatore generale',
	executiveProducers: 'Produttori esecutivi',
	distributor: 'Distributore',
	salesAgent: 'Sales agent',
	firstAssistantDirector: 'Aiuto regista',
	synopsis: 'Sinossi',
	productionNotes: 'Note di produzione',
	duration: 'Durata',
	minutes: 'Minuti',
	year: 'Anno',
	typology: 'Tipologia',
	festivals: 'Festivals',
	links: 'Links',
	competition: 'In Concorso',
	award: 'Premio',
	productionsLabels: {
		production: 'Produzione',
		addProduction: 'Aggiungi produzione',
		deleteProduction: 'Cancella produzione',
	},
	producersLabels: {
		producer: 'Produttore',
		addProducer: 'Aggiungi produttore',
		deleteProducer: 'Cancella produttore',
	},
	coProductionsLabels: {
		coProduction: 'Co-produzione',
		addCoProduction: 'Aggiungi co-produzione',
		deleteCoProduction: 'Cancella co-produzione',
	},
	coProducersLabels: {
		coProducer: 'Co-produttore',
		addCoProducer: 'Aggiungi co-produttore',
		deleteCoProducer: 'Cancella co-produttore',
	},
	actorsLabels: {
		actor: 'Attore',
		role: 'Ruolo',
		addActor: 'Aggiungi attore',
		deleteActor: 'Cancella attore',
	},
	subjectsLabels: {
		subject: 'Scrittore soggetto',
		addSubject: 'Aggiungi scrittore soggetto',
		deleteSubject: 'Cancella scrittore soggetto',
	},
	screenwritersLabels: {
		screenwriter: 'Sceneggiatore',
		addScreenwriter: 'Aggiungi sceneggiatore',
		deleteScreenwriter: 'Cancella sceneggiatore',
	},
	executiveProducersLabels: {
		executiveProducer: 'Produttore esecutivo',
		addExecutiveProducer: 'Aggiungi produttore esecutivo',
		deleteExecutiveProducer: 'Cancella produttore esecutivo',
	},
	festivalsLabels: {
		festival: 'Festival',
		addFestival: 'Aggiungi festival',
		deleteFestival: 'Cancella festival',
	},
	cover: 'Copertina del film',
	profileCover: 'Foto del profilo',
	role: 'Ruolo',
	bio: 'Biografia',
	insertAction: 'Inserisci',
	modifyAction: 'Modifica',
	confirmAction: 'Conferma',
	signInAction: 'Accedi',
	createAccount: 'Crea account',
	modify: 'Modifica',
	remove: 'Rimuovi',
	labels: {
		signUpLabel: 'Crea il tuo account',
		loginLabel: 'Login',
		passwordLabel: 'Inserisci la nuova password',
		forgotLabel: 'Se hai dimenticato la password clicca qui',
		emailLabel: 'Inserisci la tua email',
		addDbFilm: 'Aggiungere un film al database',
		modifyDbFilm: 'Modificare un film del database',
		addDbContact: 'Aggiungere un contatto al database',
		modifyDbContact: 'Modificare un contatto del database',
	},
	linksLabels: {
		trailer: 'Trailer',
		imdb: 'Link imdb',
		instagram: 'Link instagram',
		facebook: 'Link facebook',
	},
	errors: {
		dbCrud:
			'Problema nella compilazione del database, effettuare nuovamente la compilazione del form',
		signUp:
			"Problema durante la creazione dell'account, compilare nuovamente il form, i dati potrebbero essere errati.",
		login:
			"Problema durante l'accesso, compilare nuovamente il form, i dati potrebbero essere errati.",
		forgotPassword:
			'Problema durante la richiesta di ripristino della password, provare a rieffettuare i passaggi',
		resetPassword:
			'Problema durante il ripristino della password, provare a rieffettuare i passaggi',
		filmError:
			'Il film selezionato non è stato trovato, tornare alla pagina precedente',
		contactError:
			'Il contatto selezionato non è stato trovato, tornare alla pagina precedente',
	},
};

export { translationIt };
