const translationIt = {
  home: "home",
  about: "Il team",
  films: "progetti",
  news: "informazioni",
  contacts: "contatti",
  filmsList: "lista dei film",
  addFilm: "aggiungi un film",
  contactsList: "lista dei contatti",
  addContact: "aggiungi un contatto",
  vision: "visione",
  visionDescription:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make",
  ethics: "etica",
  ethicsDescription:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make",
  team: "il team",
  teamDescription:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make",
  genericInfo: {
    name: "nome",
    surname: "cognome",
    email: "email",
    number: "numero di telefono",
  },
  password: "password",
  confirmPassword: "conferma password",
  title: "titolo",
  director: "regista",
  production: "produzione",
  screenwriter: "sceneggiatore",
  directorOfPhotography: "direttore della fotografia",
  synopsis: "sinossi",
  duration: "durata",
  year: "anno",
  typology: "tipologia",
  cover: "copertina del film",
  profileCover: "foto del profilo",
  role: "ruolo",
  bio: "biografia",
  insertAction: "inserisci",
  modifyAction: "modifica",
};

export { translationIt };
